Generate new library version
mxenabled/atrium-go pull request #15
Opened 2018-11-29 21:40 UTC by brettmortensen

First cut at generating a new version of the wrapper library using
code-gen tools.

The generated stock file structure does not look right, I'm thinking of separating the models into a `models` directory and api files into a `client` directory.

Any feedback is appreciated 👍 

@film42 @minond

2018-11-30 04:30 UTC, minond requested changes
At first glance things look OK to me. Just the package name issue (can't have a hyphen and it should just be "atrium" IMO) and the ClientID key issue, that's all I noticed. If you need a hand running some of this code LMK.

2018-11-30 04:30 UTC, minond commented on api_connect_widget.go
> +package atrium-go
This is a syntax error.

2018-11-30 04:30 UTC, minond commented on api_connect_widget.go
> +		if auth, ok := ctx.Value(ContextAPIKey).(APIKey); ok {
Looks to be using the same key (`ContextAPIKey`) for both the API key and the Client ID values.

2018-11-30 04:30 UTC, minond commented on client.go
> +		} else if strings.Contains(contentType, "json") {
Oh nice, this should take care of the decoding issue.

2018-11-30 04:31 UTC, minond commented
@brettmortensen what were the issues we found the first time we tried this? Client ID, weird request/response types, json decoding failing by default, anything else?

2018-11-30 14:28 UTC, film42 commented on README.md
> +import "./atrium-go"
This is wrong. You'll be importing `github.com/mxenabled/atrium-go`.

2018-11-30 14:29 UTC, film42 commented on LICENSE
> -The MIT License (MIT)
Why are we removing the MIT license? This code is open source and free to use/ change.

2018-11-30 23:29 UTC, brettmortensen commented
@minond I believe you listed all of the issues we found above. I think they have all been resolved now besides the generic request/response types.

2018-12-01 00:47 UTC, minond commented
@brettmortensen just messaged you some solutions for the type issues we are running into. Let me know if they help.

2018-12-03 20:07 UTC, brettmortensen commented
@minond Thanks, I've updated the library with the solution you suggested. It appears to solve the issue we were seeing with the interfaces. Let me know what you think 👍

2018-12-03 23:02 UTC, minond commented
@brettmortensen that's awesome. I took a quick peek at the user create payload body and it looks like it's still using an `interface{}`. Did all of the definitions get updated or just some of them?

2018-12-03 23:04 UTC, minond commented
I take back my last comment. I'll take a look later today when I free up a bit more!

2018-12-13 00:49 UTC, minond commented
Looking good to me. I like the new constructors you created, really cleans things up. Digging around and the types look much cleaner as well -- happy not to see any `interface{}`'s. The only thing I don't like is the whole "attributes" convention that we have right now. For example, `User` is defined as

```go
type User struct {
	User *UserAttributes `json:"user,omitempty"`
}
```

so creating one requires doing

```go
user := atrium.User{
	User: &atrium.UserAttributes{
		Guid: "123",
	},
}
```

but really I just want to be able to

```
user := atrium.User{
	Guid: "123",
}
```

I'm not sure if there's a reason we're having to do this right now, but if we could do away with a "ModelAttribute" and just work with a "Model" that'd be nice. I think we should clean this up before releasing this.

The other thing is more a nitpick than anything else, and that's that we should follow Go's naming convention for things like "URL", "GUID", "ID", etc. Running a linter on this project (https://github.com/golang/lint) I'm seeing lots of warnings about "userGuid" needing to be "userGUID", "MediumLogoUrl" needing to be "MediumLogoURL", and so on. If you do a `go get -u golang.org/x/lint/golint` and then run `golint` at the root of this project you can see the full list yourself. You'll see warnings about missing comments, using underscores, and a few other naming conventions not being followed. I say we focus on properly naming model fields (eg `User.Guid -> User.GUID`) and API objects (eg `client.UsersApi -> client.UsersAPI`) right now and worry less about the rest for now. I think those names are more important since users will actually be using those.

2018-12-13 21:35 UTC, brettmortensen commented
@minond Thanks, great feedback. 

The naming of the model fields and API objects has been updated.

Good point about the "attributes" pattern I followed. When setting this up originally, I followed some swagger examples that used the same pattern. I've been searching/trying to get rid of the nested "attributes" model, but it doesn't appear there is an easy way to do that in the generators. Any time there are nested objects, it forces them to be individual objects 👎

2018-12-14 16:55 UTC, brettmortensen commented
@minond I just updated the models with the "request"/"response" pattern we discussed yesterday offline. It should clear up the confusion with the previous "attributes" pattern.

2018-12-17 23:35 UTC, film42 commented
:shipit: 

Let's make sure to tag this as `v2.0.0`.

2018-12-17 23:43 UTC, merged